const{createApp}=Vue;createApp({components:{HeaderComponent,FooterComponent,CookieConsent}}).mount('#app');

const $=id=>document.getElementById(id),s={img:null,frames:[],x:8,y:1,sel:-1,tool:'move',zoom:4,pan:{x:0,y:0},down:false,last:null,charged:false,history:[],redo:[],play:false,playAt:0,t:0};const cv=$('lia-canvas'),ctx=cv.getContext('2d');
function msg(v){$('lia-status').textContent=v}function fw(){return s.img?Math.floor(s.img.width/s.x):0}function fh(){return s.img?Math.floor(s.img.height/s.y):0}function fit(){cv.width=cv.clientWidth*devicePixelRatio;cv.height=cv.clientHeight*devicePixelRatio;draw()}addEventListener('resize',fit);
function frame(i){let w=fw(),h=fh(),c=document.createElement('canvas');c.width=w+40;c.height=h+40;let q=c.getContext('2d'),col=i%s.x,row=Math.floor(i/s.x);q.drawImage(s.img,col*w-20,(s.y-1-row)*h-20,w+40,h+40,0,0,w+40,h+40);return{c,ox:0,oy:0,vis:true,drop:false,base:q.getImageData(0,0,c.width,c.height)}}
async function split(){if(!s.img)return msg('请先选择图片。');let x=+$('lia-x').value,y=+$('lia-y').value;if(!x||!y)return msg('X/Y 必须大于 0。');if(!s.charged){let r=await fetch('/api/tool_api.asp?a=layered_image_align_split',{credentials:'same-origin',cache:'no-store'}),p=await r.json();if(!p.success)return msg(p.message||'生成图层失败');s.charged=true} s.x=x;s.y=y;s.frames=Array.from({length:x*y},(_,i)=>frame(i));s.sel=0;s.history=[];s.redo=[];renderFrames();fit();msg('已生成 '+s.frames.length+' 个图层。')}
function renderFrames(){let el=$('lia-frames');el.innerHTML='';s.frames.forEach((f,i)=>{let d=document.createElement('div');d.className='frame '+(i===s.sel?'active':'');d.innerHTML='<button>帧'+(i+1)+(f.drop?' [丢弃]':'')+'</button>'+ '<button class="eye">'+(f.vis?'●':'○')+'</button><button>'+(f.drop?'↺':'×')+'</button>';d.children[0].onclick=()=>{s.sel=i;renderFrames();draw()};let eye=d.children[1];eye.onmousedown=e=>{if(e.alt)s.frames.forEach(x=>x.vis=!f.vis);else{s.eye=!f.vis;f.vis=s.eye}renderFrames();draw()};eye.onmouseenter=()=>{if(s.eye!==undefined&&f.vis!==s.eye){f.vis=s.eye;renderFrames();draw()}};d.children[2].onclick=()=>{f.drop=!f.drop;renderFrames();draw()};el.appendChild(d)})}addEventListener('mouseup',()=>delete s.eye)
function pos(){let f=s.frames[s.sel],w=fw(),h=fh();return{x:cv.width/2/devicePixelRatio-w*s.zoom/2+s.pan.x+f.ox-20*s.zoom,y:cv.height/2/devicePixelRatio-h*s.zoom/2+s.pan.y+f.oy-20*s.zoom}}
function draw(){let W=cv.width/devicePixelRatio,H=cv.height/devicePixelRatio;ctx.setTransform(devicePixelRatio,0,0,devicePixelRatio,0,0);ctx.clearRect(0,0,W,H);ctx.fillStyle='#121419';ctx.fillRect(0,0,W,H);if(!s.frames.length)return;let current=s.play?s.playAt:s.sel;s.frames.forEach((f,i)=>{if(!f.vis||f.drop||i===current)return;let p=posFor(f);ctx.globalAlpha=.3;ctx.imageSmoothingEnabled=false;ctx.drawImage(f.c,p.x,p.y,f.c.width*s.zoom,f.c.height*s.zoom)});let f=s.frames[current];if(f){let p=posFor(f);ctx.globalAlpha=1;ctx.drawImage(f.c,p.x,p.y,f.c.width*s.zoom,f.c.height*s.zoom)}ctx.globalAlpha=1}
function posFor(f){let w=fw(),h=fh();return{x:cv.width/devicePixelRatio/2-w*s.zoom/2+s.pan.x+f.ox-20*s.zoom,y:cv.height/devicePixelRatio/2-h*s.zoom/2+s.pan.y+f.oy-20*s.zoom}}
function snapshot(){let f=s.frames[s.sel];s.history.push({i:s.sel,d:f.c.getContext('2d').getImageData(0,0,f.c.width,f.c.height)});if(s.history.length>30)s.history.shift();s.redo=[]}function undo(){let h=s.history.pop();if(!h)return;let f=s.frames[h.i],q=f.c.getContext('2d');s.redo.push({i:h.i,d:q.getImageData(0,0,f.c.width,f.c.height)});q.putImageData(h.d,0,0);draw()}function redo(){let h=s.redo.pop();if(!h)return;snapshot();s.frames[h.i].c.getContext('2d').putImageData(h.d,0,0);draw()}
function pixel(e){let f=s.frames[s.sel],p=posFor(f),x=Math.floor((e.offsetX-p.x)/s.zoom),y=Math.floor((e.offsetY-p.y)/s.zoom);return x>=0&&y>=0&&x<f.c.width&&y<f.c.height?{x,y}:null}function dot(p,restore){let f=s.frames[s.sel],q=f.c.getContext('2d'),r=+$('lia-size').value;if(restore){let d=q.getImageData(0,0,f.c.width,f.c.height),b=f.base.data;for(let y=-r;y<=r;y++)for(let x=-r;x<=r;x++)if(x*x+y*y<=r*r){let k=((p.y+y)*f.c.width+p.x+x)*4;if(k>=0&&k<b.length){d.data[k]=b[k];d.data[k+1]=b[k+1];d.data[k+2]=b[k+2];d.data[k+3]=b[k+3]}}q.putImageData(d,0,0)}else if(s.tool==='erase'){q.save();q.globalCompositeOperation='destination-out';q.beginPath();q.arc(p.x,p.y,r,0,7);q.fill();q.restore()}else{q.fillStyle=$('lia-color').value;q.globalAlpha=+$('lia-alpha').value;q.beginPath();q.arc(p.x,p.y,r,0,7);q.fill();q.globalAlpha=1}}function paint(e,restore){let p=pixel(e);if(!p)return;if(s.lastPaint){let n=Math.max(Math.abs(p.x-s.lastPaint.x),Math.abs(p.y-s.lastPaint.y));for(let i=1;i<=n;i++)dot({x:Math.round(s.lastPaint.x+(p.x-s.lastPaint.x)*i/n),y:Math.round(s.lastPaint.y+(p.y-s.lastPaint.y)*i/n)},restore)}else dot(p,restore);s.lastPaint=p;draw()}
cv.onwheel=e=>{e.preventDefault();let old=s.zoom;s.zoom=Math.max(1,Math.min(32,s.zoom-e.deltaY*.01));let r=s.zoom/old;s.pan.x=(s.pan.x-(e.offsetX-cv.clientWidth/2))*r+(e.offsetX-cv.clientWidth/2);s.pan.y=(s.pan.y-(e.offsetY-cv.clientHeight/2))*r+(e.offsetY-cv.clientHeight/2);draw()};cv.onmousedown=e=>{if(e.button===1){s.down='pan';s.last=e;return}if(e.button||s.tool==='move')return;if(e.ctrl){s.down='size';s.last=e;return}let p=pixel(e);if(e.alt&&s.tool==='brush'&&p){let d=s.frames[s.sel].c.getContext('2d').getImageData(p.x,p.y,1,1).data;$('lia-color').value='#'+[d[0],d[1],d[2]].map(x=>x.toString(16).padStart(2,'0')).join('');return}snapshot();s.down='paint';s.lastPaint=null;paint(e,e.alt&&s.tool==='erase')};cv.onmousemove=e=>{if(s.down==='pan'){s.pan.x+=e.clientX-s.last.clientX;s.pan.y+=e.clientY-s.last.clientY;s.last=e;draw()}else if(s.down==='size'){let v=$('lia-size');v.value=Math.max(1,Math.min(64,+v.value+Math.sign(e.clientX-s.last.clientX)));s.last=e}else if(s.down==='paint')paint(e,e.alt&&s.tool==='erase')};onmouseup=()=>{s.down=false;s.lastPaint=null};
addEventListener('keydown',e=>{if(!s.frames.length)return;if(e.ctrl&&e.key==='z'){undo();return}if(e.ctrl&&e.key==='y'){redo();return}if('zxc'.includes(e.key)){s.tool={z:'move',x:'erase',c:'brush'}[e.key];document.querySelectorAll('[data-tool]').forEach(b=>b.classList.toggle('active',b.dataset.tool===s.tool));return}if(s.tool!=='move')return;let f=s.frames[s.sel],d=e.shiftKey?3:1;if(e.key==='a')f.ox-=d;if(e.key==='d')f.ox+=d;if(e.key==='w')f.oy-=d;if(e.key==='s')f.oy+=d;if(e.key==='q')s.sel=Math.max(0,s.sel-1);if(e.key==='e')s.sel=Math.min(s.frames.length-1,s.sel+1);renderFrames();draw()});
function align(i,m){let f=s.frames[i],q=f.c.getContext('2d'),d=q.getImageData(20,20,fw(),fh()).data,minX=fw(),maxX=-1,minY=fh(),maxY=-1;for(let y=0;y<fh();y++)for(let x=0;x<fw();x++)if(d[(y*fw()+x)*4+3]>12){minX=Math.min(minX,x);maxX=Math.max(maxX,x);minY=Math.min(minY,y);maxY=Math.max(maxY,y)}if(maxX<0)return;if(m!=='y')f.ox=fw()/2-(minX+maxX)/2;if(m!=='x')f.oy=-(fh()/2-(minY+maxY)/2)}
document.querySelectorAll('[data-tool]').forEach(b=>b.onclick=()=>{s.tool=b.dataset.tool;document.querySelectorAll('[data-tool]').forEach(x=>x.classList.toggle('active',x===b))});document.querySelectorAll('[data-align]').forEach(b=>b.onclick=()=>{align(s.sel,b.dataset.align);draw()});document.querySelectorAll('[data-align-all]').forEach(b=>b.onclick=()=>{s.frames.forEach((_,i)=>align(i,b.dataset.alignAll));draw()});$('lia-file').onchange=e=>{let f=e.target.files[0];if(!f)return;s.charged=false;$('lia-name').textContent=f.name;let im=new Image;im.onload=()=>{s.img=im;s.frames=[];s.sel=-1;fit();msg('设置 X/Y 后生成图层。')};im.src=URL.createObjectURL(f)};$('lia-split').onclick=split;$('lia-reset').onclick=()=>{s.frames.forEach(f=>{f.ox=f.oy=0});draw()};$('lia-undo').onclick=undo;$('lia-redo').onclick=redo;$('lia-save').onclick=()=>{let keep=s.frames.filter(f=>!f.drop);if(!keep.length)return msg('没有保留的帧。');let ny=Math.min(s.y,keep.length),nx=Math.ceil(keep.length/ny),o=document.createElement('canvas');o.width=nx*fw();o.height=ny*fh();let q=o.getContext('2d');keep.forEach((f,i)=>{let x=i%nx*fw(),y=(ny-1-Math.floor(i/nx))*fh();q.drawImage(f.c,20-f.ox,20+f.oy,fw(),fh(),x,y,fw(),fh())});let a=document.createElement('a');a.href=o.toDataURL('image/png');a.download=($('lia-name').textContent||'对位图')+'_编辑.png';a.click()};$('lia-play').onclick=()=>{s.play=!s.play;$('lia-play').textContent=s.play?'停止':'播放';if(s.play){s.t=performance.now();s.playAt=s.sel;requestAnimationFrame(play)}};function play(n){if(!s.play)return;if(n-s.t>1000/(+$('lia-fps').value||10)){let v=s.frames.map((f,i)=>f.vis&&!f.drop?i:null).filter(i=>i!==null),k=v.indexOf(s.playAt);s.playAt=v[(k+1)%v.length];s.t=n;draw()}requestAnimationFrame(play)}fit();

function liaOutput(){let keep=s.frames.filter(f=>!f.drop);if(!keep.length){msg('没有保留的帧。');return null}let ny=Math.min(s.y,keep.length),nx=Math.ceil(keep.length/ny),o=document.createElement('canvas');o.width=nx*fw();o.height=ny*fh();let q=o.getContext('2d');keep.forEach((f,i)=>{let x=i%nx*fw(),y=(ny-1-Math.floor(i/nx))*fh();q.drawImage(f.c,20-f.ox,20+f.oy,fw(),fh(),x,y,fw(),fh())});return o}
let cover=document.createElement('button');cover.type='button';cover.textContent='保存覆盖';document.querySelector('.lia-top').insertBefore(cover,$('lia-save'));cover.onclick=async()=>{let out=liaOutput();if(!out)return;if(!window.showSaveFilePicker){$('lia-save').click();return}try{let h=await showSaveFilePicker({suggestedName:($('lia-name').textContent||'对位图').replace(/\.[^.]+$/,'')+'.png',types:[{description:'PNG 图片',accept:{'image/png':['.png']}}]});let w=await h.createWritable();await w.write(await new Promise(r=>out.toBlob(r,'image/png')));await w.close();msg('已保存覆盖。')}catch(e){if(e.name!=='AbortError')msg('保存覆盖失败，已取消。')}};
let cursor=document.createElement('i');cursor.style.cssText='position:absolute;border:1px solid #fff;border-radius:50%;pointer-events:none;display:none;box-sizing:border-box;z-index:2';document.querySelector('.lia-center').appendChild(cursor);cv.addEventListener('mousemove',e=>{if(s.tool==='move'||!s.frames.length){cursor.style.display='none';return}let d=(+$('lia-size').value*2+2)*s.zoom;cursor.style.cssText+=';display:block;width:'+d+'px;height:'+d+'px;left:'+(e.offsetX-d/2)+'px;top:'+(e.offsetY-d/2)+'px'});cv.addEventListener('mouseleave',()=>cursor.style.display='none');

function frame(i){let w=fw(),h=fh(),c=document.createElement('canvas');c.width=w+40;c.height=h+40;let q=c.getContext('2d'),col=i%s.x,row=Math.floor(i/s.x),sx=col*w,sy=(s.y-1-row)*h,ex=20;q.clearRect(0,0,c.width,c.height);q.drawImage(s.img,sx,sy,w,h,ex,ex,w,h);if(sy+h<s.img.height){let n=Math.min(ex,s.img.height-sy-h);q.drawImage(s.img,sx,sy+h,w,n,ex,ex+h,w,n)}if(sy>0){let n=Math.min(ex,sy);q.drawImage(s.img,sx,sy-n,w,n,ex,ex-n,w,n)}if(sx>0){let n=Math.min(ex,sx);q.drawImage(s.img,sx-n,sy,n,h,ex-n,ex,n,h)}if(sx+w<s.img.width){let n=Math.min(ex,s.img.width-sx-w);q.drawImage(s.img,sx+w,sy,n,h,ex+w,ex,n,h)}return{c,ox:0,oy:0,vis:true,drop:false,base:q.getImageData(0,0,c.width,c.height)}}
function draw(){let W=cv.width/devicePixelRatio,H=cv.height/devicePixelRatio;ctx.setTransform(devicePixelRatio,0,0,devicePixelRatio,0,0);ctx.clearRect(0,0,W,H);ctx.fillStyle='#121419';ctx.fillRect(0,0,W,H);if(!s.frames.length)return;let current=s.play?s.playAt:s.sel;s.frames.forEach((f,i)=>{if(!f.vis||f.drop||i===current)return;let p=posFor(f);ctx.globalAlpha=.3;ctx.imageSmoothingEnabled=false;ctx.drawImage(f.c,p.x,p.y,f.c.width*s.zoom,f.c.height*s.zoom)});let f=s.frames[current];if(!f)return;let p=posFor(f);ctx.globalAlpha=1;ctx.imageSmoothingEnabled=false;ctx.drawImage(f.c,p.x,p.y,f.c.width*s.zoom,f.c.height*s.zoom);let x=p.x+20*s.zoom,y=p.y+20*s.zoom,w=fw()*s.zoom,h=fh()*s.zoom;ctx.fillStyle='rgba(0,0,0,.85)';ctx.fillRect(0,0,W,y);ctx.fillRect(0,y+h,W,H-y-h);ctx.fillRect(0,y,x,h);ctx.fillRect(x+w,y,W-x-w,h);ctx.globalAlpha=1}
function dot(p,restore){let f=s.frames[s.sel],q=f.c.getContext('2d'),r=+$('lia-size').value;if(restore){let d=q.getImageData(0,0,f.c.width,f.c.height),b=f.base.data;for(let y=-r;y<=r;y++)for(let x=-r;x<=r;x++)if(x*x+y*y<=r*r){let px=p.x+x,py=p.y+y;if(px>=20&&px<20+fw()&&py>=20&&py<20+fh()){let k=(py*f.c.width+px)*4;d.data[k]=b[k];d.data[k+1]=b[k+1];d.data[k+2]=b[k+2];d.data[k+3]=b[k+3]}}q.putImageData(d,0,0)}else if(s.tool==='erase'){q.save();q.globalCompositeOperation='destination-out';q.beginPath();q.arc(p.x,p.y,r,0,7);q.fill();q.restore()}else{q.fillStyle=$('lia-color').value;q.globalAlpha=+$('lia-alpha').value;q.beginPath();q.arc(p.x,p.y,r,0,7);q.fill();q.globalAlpha=1}}
function liaOutput(){let keep=s.frames.filter(f=>!f.drop);if(!keep.length){msg('没有保留的帧。');return null}let ny=Math.min(s.y,keep.length),nx=Math.ceil(keep.length/ny),o=document.createElement('canvas');o.width=nx*fw();o.height=ny*fh();let q=o.getContext('2d'),out=q.createImageData(o.width,o.height);keep.forEach((f,i)=>{let d=f.c.getContext('2d').getImageData(0,0,f.c.width,f.c.height).data,dx=Math.round(f.ox),dy=Math.round(f.oy),ox=i%nx*fw(),oy=(ny-1-Math.floor(i/nx))*fh();for(let py=0;py<fh();py++)for(let px=0;px<fw();px++){let sx=px+20-dx,sy=py+20+dy;if(sx<0||sy<0||sx>=f.c.width||sy>=f.c.height)continue;let a=(sy*f.c.width+sx)*4,b=((oy+py)*o.width+ox+px)*4;out.data[b]=d[a];out.data[b+1]=d[a+1];out.data[b+2]=d[a+2];out.data[b+3]=d[a+3]}});q.putImageData(out,0,0);return o}
function renderFrames(){let el=$('lia-frames');el.innerHTML='';s.frames.forEach((f,i)=>{let d=document.createElement('div');d.className='frame '+(i===s.sel?'active':'');d.innerHTML='<button>帧'+(i+1)+(f.drop?' [丢弃]':'')+'</button><button class="eye">'+(f.vis?'●':'○')+'</button><button>'+(f.drop?'↺':'×')+'</button>';d.children[0].onclick=()=>{s.sel=i;renderFrames();draw()};let eye=d.children[1];eye.onmousedown=e=>{s.eyeValue=e.alt?!f.vis:!f.vis;if(e.alt){s.frames.forEach(x=>x.vis=s.eyeValue);renderFrames()}else{f.vis=s.eyeValue;eye.textContent=f.vis?'●':'○'}draw()};eye.onmouseenter=()=>{if(s.eyeValue!==undefined&&f.vis!==s.eyeValue){f.vis=s.eyeValue;eye.textContent=f.vis?'●':'○';draw()}};d.children[2].onclick=()=>{f.drop=!f.drop;renderFrames();draw()};el.appendChild(d)})}addEventListener('mouseup',()=>delete s.eyeValue)

$('lia-file').accept='image/png,.png';$('lia-size').min='0';document.querySelector('.lia-right').style.overflow='hidden';$('lia-frames').style.cssText='max-height:430px;overflow:auto;margin-top:8px';cover.onclick=async()=>{let out=liaOutput();if(!out)return;let keep=s.frames.filter(f=>!f.drop),ny=Math.min(s.y,keep.length),nx=Math.ceil(keep.length/ny);if(!confirm('覆盖原图?\n新尺寸: '+nx+'×'+ny+' ('+out.width+'×'+out.height+'px)'))return;if(!window.showSaveFilePicker){$('lia-save').click();return}try{let h=await showSaveFilePicker({suggestedName:($('lia-name').textContent||'对位图').replace(/\.[^.]+$/,'')+'.png',types:[{description:'PNG 图片',accept:{'image/png':['.png']}}]}),w=await h.createWritable();await w.write(await new Promise(r=>out.toBlob(r,'image/png')));await w.close();msg('已保存覆盖。')}catch(e){if(e.name!=='AbortError')msg('保存覆盖失败，已取消。')}};

function snapshot(){let f=s.frames[s.sel];if(!f)return;s.history.push(f.c.getContext('2d').getImageData(0,0,f.c.width,f.c.height));if(s.history.length>30)s.history.shift();s.redo=[]}function undo(){let h=s.history.pop(),f=s.frames[s.sel];if(!h||!f)return;let q=f.c.getContext('2d');s.redo.push(q.getImageData(0,0,f.c.width,f.c.height));q.putImageData(h,0,0);draw()}function redo(){let h=s.redo.pop(),f=s.frames[s.sel];if(!h||!f)return;let q=f.c.getContext('2d');s.history.push(q.getImageData(0,0,f.c.width,f.c.height));q.putImageData(h,0,0);draw()}

const liaGesture=document.createElement('div');liaGesture.style.cssText='position:absolute;display:none;z-index:3;pointer-events:none;color:#fff;font-size:12px;line-height:18px;text-align:center';document.querySelector('.lia-center').appendChild(liaGesture);
function liaHistory(i=s.sel){let f=s.frames[i];if(!f)return;s.history.push({i,d:f.c.getContext('2d').getImageData(0,0,f.c.width,f.c.height),ox:f.ox,oy:f.oy});if(s.history.length>30)s.history.shift();s.redo=[]}function snapshot(){liaHistory()}function undo(){let h=s.history.pop();if(!h)return;let f=s.frames[h.i];if(!f)return;s.redo.push({i:h.i,d:f.c.getContext('2d').getImageData(0,0,f.c.width,f.c.height),ox:f.ox,oy:f.oy});f.c.getContext('2d').putImageData(h.d,0,0);f.ox=h.ox;f.oy=h.oy;s.sel=h.i;renderFrames();draw()}function redo(){let h=s.redo.pop();if(!h)return;let f=s.frames[h.i];if(!f)return;s.history.push({i:h.i,d:f.c.getContext('2d').getImageData(0,0,f.c.width,f.c.height),ox:f.ox,oy:f.oy});f.c.getContext('2d').putImageData(h.d,0,0);f.ox=h.ox;f.oy=h.oy;s.sel=h.i;renderFrames();draw()}
function liaCursor(e){if(s.tool==='move'||!s.frames.length){cursor.style.display='none';return}let d=(+$('lia-size').value*2+2)*s.zoom;cursor.style.cssText='position:absolute;border:1px solid #fff;border-radius:50%;pointer-events:none;display:block;box-sizing:border-box;z-index:2;width:'+d+'px;height:'+d+'px;left:'+(e.offsetX-d/2)+'px;top:'+(e.offsetY-d/2)+'px'}function liaSample(e){let p=pixel(e);if(!p)return;let d=s.frames[s.sel].c.getContext('2d').getImageData(p.x,p.y,1,1).data;$('lia-color').value='#'+[d[0],d[1],d[2]].map(x=>x.toString(16).padStart(2,'0')).join('');msg('已吸取颜色。')}function liaAlpha(e){let a=+$('lia-alpha').value,c=$('lia-color').value;liaGesture.style.cssText='position:absolute;display:block;z-index:3;pointer-events:none;color:#fff;font-size:12px;line-height:18px;text-align:center;left:'+(e.offsetX+14)+'px;top:'+(e.offsetY+14)+'px';liaGesture.innerHTML='<i style="display:block;width:20px;height:20px;margin:auto;border:1px solid #fff;border-radius:3px;background:'+c+';opacity:'+a+'"></i>'+Math.round(a*100)+'%'}
cv.onmousedown=e=>{if(e.button===1){s.down='pan';s.last=e;return}if(e.button||s.tool==='move'||!s.frames.length)return;if(e.ctrl){s.down='size';s.last=e;s.startSize=+$('lia-size').value;s.gestureMoved=false;return}if(e.alt){s.down='alpha';s.last=e;s.startAlpha=+$('lia-alpha').value;s.gestureMoved=false;liaAlpha(e);return}snapshot();s.down='paint';s.lastPaint=null;paint(e,false)};cv.onmousemove=e=>{liaCursor(e);if(s.down==='pan'){s.pan.x+=e.clientX-s.last.clientX;s.pan.y+=e.clientY-s.last.clientY;s.last=e;draw();return}if(s.down==='size'){let delta=e.clientX-s.last.clientX;if(Math.abs(delta)>=4){$('lia-size').value=Math.max(0,Math.min(64,s.startSize+Math.round(delta/4)));s.gestureMoved=true;liaCursor(e)}return}if(s.down==='alpha'){let delta=e.clientY-s.last.clientY;if(Math.abs(delta)>=3){$('lia-alpha').value=Math.max(0,Math.min(1,s.startAlpha-delta/160));s.gestureMoved=true}liaAlpha(e);return}if(s.down==='paint')paint(e,false)};addEventListener('mouseup',e=>{if(s.down==='size'&&!s.gestureMoved)liaSample(e);s.down=false;s.lastPaint=null;liaGesture.style.display='none'});cv.addEventListener('mouseleave',()=>liaGesture.style.display='none');
addEventListener('keydown',e=>{if(!s.frames.length||e.target.matches('input,textarea,select'))return;let k=e.key.toLowerCase();if(e.ctrl&&(k==='z'||k==='y')){e.preventDefault();e.stopImmediatePropagation();k==='z'?undo():redo();return}if('zxc'.includes(k)){e.stopImmediatePropagation();s.tool={z:'move',x:'erase',c:'brush'}[k];document.querySelectorAll('[data-tool]').forEach(b=>b.classList.toggle('active',b.dataset.tool===s.tool));return}if(s.tool!=='move'||!['a','d','w','s','q','e'].includes(k))return;e.preventDefault();e.stopImmediatePropagation();let f=s.frames[s.sel],d=e.shiftKey?3:1;if('adws'.includes(k))liaHistory();if(k==='a')f.ox-=d;if(k==='d')f.ox+=d;if(k==='w')f.oy-=d;if(k==='s')f.oy+=d;if(k==='q')s.sel=Math.max(0,s.sel-1);if(k==='e')s.sel=Math.min(s.frames.length-1,s.sel+1);renderFrames();draw()},true);

document.querySelector('.lia-help').insertAdjacentHTML('beforeend','<p>画笔和橡皮：Ctrl+左键单击吸取颜色，Ctrl+左键左右拖拽调整大小；Alt+左键上下拖拽调整透明度，指针旁会显示当前透明度色块。画布内的移动、画笔和橡皮操作均可使用 Ctrl+Z / Ctrl+Y 撤销或重做。</p>');
addEventListener('mouseup',e=>{if(s.down==='size'&&!s.gestureMoved)liaSample(e);s.down=false;s.lastPaint=null;liaGesture.style.display='none'},true);

cover.remove();const liaSave=$('lia-save');liaSave.textContent='保存到我的图片';liaSave.onclick=async()=>{let out=liaOutput();if(!out)return;liaSave.disabled=true;liaSave.textContent='保存中...';try{let r=await fetch('/api/tool_api.asp?a=layered_image_align_save',{method:'POST',credentials:'same-origin',headers:{'Content-Type':'application/x-www-form-urlencoded;charset=UTF-8'},body:new URLSearchParams({image_data:out.toDataURL('image/png')})}),p=await r.json();if(!p.success)throw new Error(p.message||'保存失败');msg('已保存到我的图片。');liaSave.textContent='已保存';setTimeout(()=>{liaSave.textContent='保存到我的图片';liaSave.disabled=false},1400)}catch(e){liaSave.disabled=false;liaSave.textContent='保存到我的图片';msg(e.message||'保存失败，请稍后重试。')}};

const liaDemo=document.createElement('section');liaDemo.style.cssText='margin-top:24px;padding-top:20px;border-top:1px solid var(--border)';liaDemo.innerHTML='<h2>工具用途</h2><p>将一张平铺精灵图拆分为多个画面，在叠加预览中逐帧对位，再用画笔和橡皮修整边缘与干扰内容，最终输出紧凑的序列帧动画。</p><img src="/assets/images/layered-image-align-demo.jpg" alt="火焰序列帧动画对位示例" loading="lazy" style="width:100%;max-width:900px;margin-top:12px;border:1px solid var(--border);background:#fff">';document.querySelector('.lia-help').appendChild(liaDemo);

cv.addEventListener('mousedown',e=>{if(e.button===1)e.preventDefault()},{capture:true});cv.addEventListener('auxclick',e=>{if(e.button===1)e.preventDefault()});cv.addEventListener('wheel',e=>e.preventDefault(),{passive:false});

const liaLibrary=document.createElement('button');liaLibrary.type='button';liaLibrary.textContent='查看我的图片';liaLibrary.hidden=true;liaLibrary.onclick=()=>window.open('/my_images.asp','_blank','noopener');liaSave.insertAdjacentElement('afterend',liaLibrary);const liaSaveToLibrary=liaSave.onclick;liaSave.onclick=async()=>{await liaSaveToLibrary();if(liaSave.textContent==='已保存')liaLibrary.hidden=false};

// Accept the current hard-bone attachment without putting a potentially large data URL in the address bar.
(function(){if(new URLSearchParams(location.search).get('source')!=='hard-bone')return;let load=event=>{let source=event.data;if(event.origin!==location.origin||!source||source.type!=='zf3d-hard-bone-layered-align-source'||!source.url)return;removeEventListener('message',load);let image=new Image;image.onload=()=>{s.img=image;s.frames=[];s.sel=-1;$('lia-name').textContent=source.name||'硬骨骼附件.png';$('lia-x').value=Math.max(1,Math.min(64,Math.round(+source.columns||1)));$('lia-y').value=Math.max(1,Math.min(64,Math.round(+source.rows||1)));fit();msg('已载入硬骨骼当前附件，确认 X/Y 后生成图层。')};image.onerror=()=>msg('硬骨骼附件读取失败，请返回后重试。');image.src=source.url};addEventListener('message',load);if(window.opener)window.opener.postMessage('zf3d-hard-bone-layered-align-ready',location.origin)})();
