const {createApp}=Vue;createApp({components:{HeaderComponent,FooterComponent,CookieConsent}}).mount('#app');
(() => {
    const maxPixels=8000000,maxRegions=300;
    const fileInput=document.getElementById('se-file'),drop=document.getElementById('se-drop'),sourceEditor=document.getElementById('se-source-editor'),resultEditor=document.getElementById('se-result-editor'),resultEmpty=document.getElementById('se-result-empty'),source=document.getElementById('se-source'),sourceCtx=source.getContext('2d',{willReadFrequently:true}),original=document.createElement('canvas'),originalCtx=original.getContext('2d',{willReadFrequently:true}),sourceWrap=document.getElementById('se-source-wrap'),layer=document.getElementById('se-region-layer'),draft=document.getElementById('se-draft'),grid=document.getElementById('se-output-grid'),refineModal=document.getElementById('se-refine-modal'),refineCanvas=document.getElementById('se-refine-canvas'),refineCtx=refineCanvas.getContext('2d'),refineWrap=document.getElementById('se-refine-wrap'),refineRing=document.getElementById('se-refine-ring'),refineName=document.getElementById('se-refine-name'),refineBackground=document.getElementById('se-refine-background'),refineClose=document.getElementById('se-refine-close');
    const colorInput=document.getElementById('se-color'),colorValue=document.getElementById('se-color-value'),cornerButton=document.getElementById('se-corner-color'),pickButton=document.getElementById('se-pick-color'),tolerance=document.getElementById('se-tolerance'),minArea=document.getElementById('se-min-area'),padding=document.getElementById('se-padding'),detectButton=document.getElementById('se-detect'),deleteButton=document.getElementById('se-delete'),clearButton=document.getElementById('se-clear'),restoreButton=document.getElementById('se-restore'),exportButton=document.getElementById('se-export'),balance=document.getElementById('se-token-balance'),prefixInput=document.getElementById('se-prefix'),fitButton=document.getElementById('se-fit'),boxesButton=document.getElementById('se-boxes'),labelsButton=document.getElementById('se-labels'),cancelRefineButton=document.getElementById('se-cancel-refine'),brush=document.getElementById('se-brush'),opacity=document.getElementById('se-opacity'),brushControls=document.getElementById('se-brush-controls'),brushRing=document.getElementById('se-brush-ring');
    const xInput=document.getElementById('se-x'),yInput=document.getElementById('se-y'),wInput=document.getElementById('se-w'),hInput=document.getElementById('se-h'),resizeWInput=document.getElementById('se-resize-w'),resizeHInput=document.getElementById('se-resize-h'),lockRatio=document.getElementById('se-lock-ratio'),resizeApply=document.getElementById('se-resize-apply');
    let imageData=null,manualRestoreMask=null,regions=[],deletedRegions=[],selectedId=null,fileBase='sprites',isExporting=false,manualStart=null,regionOperation=null,eraseOperation=null,bulkStart=null,brushAdjust=null,lastPaintPoint=null,paintRefreshQueued=false,pickMode=false,picking=false,editMode='select',showBoxes=true,showLabels=true,refineRegion=null,refinePaint=null,refinePan=null,refineBrushAdjust=null,refineLastPaint=null;
    const sourceView={scale:1,x:0,y:0},refineView={scale:1,x:0,y:0};
    function setStatus(message){document.getElementById('se-status').textContent=message||'';}
    function hexPart(value){return ('0'+Math.max(0,Math.min(255,Math.round(value))).toString(16)).slice(-2);}
    function setColor(r,g,b){const value='#'+hexPart(r)+hexPart(g)+hexPart(b);colorInput.value=value;colorValue.textContent=value.toUpperCase();}
    function rgb(){const value=colorInput.value;return {r:parseInt(value.slice(1,3),16),g:parseInt(value.slice(3,5),16),b:parseInt(value.slice(5,7),16)};}
    function setPickMode(active){pickMode=active;picking=false;pickButton.classList.toggle('se-pick-active',active);sourceWrap.classList.toggle('se-picking',active);source.style.cursor=active?'crosshair':(editMode==='erase'?'crosshair':'');}
    function pickBackground(event){const point=pointerImagePoint(event),pixel=sourceCtx.getImageData(point.x,point.y,1,1).data;setColor(pixel[0],pixel[1],pixel[2]);renderOutput();if(refineRegion)drawRefine();}
    function setValue(input,id){document.getElementById(id).textContent=input.value;}
    [[tolerance,'se-tolerance-value'],[minArea,'se-min-area-value'],[padding,'se-padding-value'],[brush,'se-brush-value']].forEach(([input,id])=>{setValue(input,id);input.addEventListener('input',()=>setValue(input,id));});opacity.addEventListener('input',()=>document.getElementById('se-opacity-value').textContent=opacity.value+'%');
    tolerance.addEventListener('input',()=>{renderOutput();if(refineRegion)drawRefine();});
    async function loadBalance(){try{const response=await fetch('/api/tool_api.asp?a=balance',{credentials:'same-origin',cache:'no-store'}),payload=await response.json();balance.textContent=payload.success?payload.data.token_balance:((payload.message||'').indexOf('登录')>=0?'登录后查看':'暂不可用');}catch(error){balance.textContent='加载失败';}}
    loadBalance();
    function detectCornerColor(){if(!imageData)return;const {data,width,height}=imageData,points=[[0,0],[width-1,0],[0,height-1],[width-1,height-1]];let r=0,g=0,b=0,count=0;points.forEach(([cx,cy])=>{for(let y=Math.max(0,cy-3);y<=Math.min(height-1,cy+3);y++)for(let x=Math.max(0,cx-3);x<=Math.min(width-1,cx+3);x++){const i=(y*width+x)*4;r+=data[i];g+=data[i+1];b+=data[i+2];count++;}});setColor(r/count,g/count,b/count);}
    function updateActions(){const ready=!!imageData,has=regions.length>0,selected=regions.some(region=>region.id===selectedId);detectButton.disabled=!ready;clearButton.disabled=!has;deleteButton.disabled=!selected;restoreButton.disabled=!deletedRegions.length;exportButton.disabled=!has||isExporting;fitButton.disabled=!ready;boxesButton.disabled=!ready;labelsButton.disabled=!ready;[xInput,yInput,wInput,hInput].forEach(input=>input.disabled=!selected);document.getElementById('se-region-count').textContent=regions.length+' 个选区';document.getElementById('se-output-count').textContent=regions.length+' 张';}
    function selectedRegion(){return regions.find(region=>region.id===selectedId)||null;}
    function removeRegion(id){const region=regions.find(item=>item.id===id);if(!region)return;deletedRegions.push(region);regions=regions.filter(item=>item.id!==id);selectedId=regions.length?regions[0].id:null;syncFields();renderRegions();renderOutput();setStatus('已删除选区。');}
    function setEditMode(mode){editMode=mode;source.style.cursor='';brushRing.style.display='none';}
    function syncFields(){const region=selectedRegion();if(!region){[xInput,yInput,wInput,hInput].forEach(input=>input.value='');updateActions();return;}xInput.value=region.x;yInput.value=region.y;wInput.value=region.w;hInput.value=region.h;updateActions();}
    function regionCanvasRect(){const canvasRect=source.getBoundingClientRect(),wrapRect=sourceWrap.getBoundingClientRect();return {canvasRect,wrapRect,scaleX:canvasRect.width/source.width,scaleY:canvasRect.height/source.height};}
    function positionRegionBox(box,region,index){const metrics=regionCanvasRect();box.style.left=(metrics.canvasRect.left-metrics.wrapRect.left+region.x*metrics.scaleX)+'px';box.style.top=(metrics.canvasRect.top-metrics.wrapRect.top+region.y*metrics.scaleY)+'px';box.style.width=Math.max(2,region.w*metrics.scaleX)+'px';box.style.height=Math.max(2,region.h*metrics.scaleY)+'px';const label=box.querySelector('.se-region-label');if(label)label.textContent=(index+1)+' · '+region.w+' x '+region.h;}
    function renderRegions(){layer.replaceChildren();if(!imageData)return;layer.classList.toggle('se-hidden-boxes',!showBoxes);layer.classList.toggle('se-hidden-labels',!showLabels);regions.forEach((region,index)=>{const box=document.createElement('div'),label=document.createElement('span');box.className='se-region'+(region.id===selectedId?' selected':'');positionRegionBox(box,region,index);label.className='se-region-label';box.appendChild(label);if(region.id===selectedId){const refine=document.createElement('button'),remove=document.createElement('button');refine.type='button';refine.className='se-region-refine';refine.textContent='精修';refine.title='精修此选区';refine.addEventListener('pointerdown',event=>event.stopPropagation());refine.addEventListener('click',event=>{event.stopPropagation();openRefine(region,index);});remove.type='button';remove.className='se-region-delete';remove.textContent='删除';remove.title='删除此选区';remove.addEventListener('pointerdown',event=>event.stopPropagation());remove.addEventListener('click',event=>{event.stopPropagation();removeRegion(region.id);});box.append(refine,remove);for(const handle of ['n','e','s','w','nw','ne','sw','se']){const node=document.createElement('span');node.className='se-handle';node.dataset.handle=handle;box.appendChild(node);}}box.addEventListener('pointerdown',event=>startRegionOperation(event,region));box.addEventListener('pointermove',moveRegionOperation);['pointerup','pointercancel','lostpointercapture'].forEach(name=>box.addEventListener(name,endRegionOperation));layer.appendChild(box);});}
    function spriteCanvas(region){const canvas=document.createElement('canvas');canvas.width=region.w;canvas.height=region.h;const ctx=canvas.getContext('2d',{willReadFrequently:true});ctx.drawImage(source,region.x,region.y,region.w,region.h,0,0,region.w,region.h);const pixels=ctx.getImageData(0,0,region.w,region.h),data=pixels.data,bg=rgb(),limit=Number(tolerance.value);let minX=region.w,minY=region.h,maxX=-1,maxY=-1;for(let y=0;y<region.h;y++)for(let x=0;x<region.w;x++){const i=(y*region.w+x)*4,sourceIndex=(region.y+y)*source.width+region.x+x,dist=Math.sqrt((data[i]-bg.r)**2+(data[i+1]-bg.g)**2+(data[i+2]-bg.b)**2);if((!manualRestoreMask||!manualRestoreMask[sourceIndex])&&dist<=limit)data[i+3]=0;if(data[i+3]>12){if(x<minX)minX=x;if(x>maxX)maxX=x;if(y<minY)minY=y;if(y>maxY)maxY=y;}}ctx.putImageData(pixels,0,0);if(maxX<minX||maxY<minY)return canvas;const tight=document.createElement('canvas');tight.width=maxX-minX+1;tight.height=maxY-minY+1;tight.getContext('2d').drawImage(canvas,minX,minY,tight.width,tight.height,0,0,tight.width,tight.height);return tight;}
    function renderOutput(){grid.replaceChildren();if(!regions.length){const empty=document.createElement('span');empty.className='se-output-empty';empty.textContent='暂无选区';grid.appendChild(empty);updateActions();return;}regions.forEach((region,index)=>{const item=document.createElement('div'),canvas=spriteCanvas(region),number=document.createElement('span'),refine=document.createElement('button'),remove=document.createElement('button');item.className='se-sprite'+(region.id===selectedId?' selected':'');item.tabIndex=0;item.setAttribute('role','button');number.textContent=String(index+1).padStart(2,'0');refine.type='button';refine.className='se-sprite-action se-sprite-refine';refine.textContent='精修';refine.title='用橡皮擦精修此图块';remove.type='button';remove.className='se-sprite-action se-sprite-delete';remove.textContent='删除';remove.title='删除此图块';item.append(canvas,number,refine,remove);const select=()=>{selectedId=region.id;syncFields();renderRegions();renderOutput();};item.addEventListener('click',select);item.addEventListener('keydown',event=>{if(event.key==='Enter'||event.key===' '){event.preventDefault();select();}});refine.addEventListener('click',event=>{event.stopPropagation();openRefine(region,index);});remove.addEventListener('click',event=>{event.stopPropagation();removeRegion(region.id);});grid.appendChild(item);});updateActions();}
    function resetRegions(){regions=[];deletedRegions=[];selectedId=null;syncFields();renderRegions();renderOutput();}
    function syncSourceSizeFields(){resizeWInput.value=source.width;resizeHInput.value=source.height;}
    function replaceSource(width,height,draw){const next=document.createElement('canvas'),nextCtx=next.getContext('2d');next.width=width;next.height=height;draw(nextCtx,next);source.width=original.width=width;source.height=original.height=height;sourceCtx.clearRect(0,0,width,height);sourceCtx.drawImage(next,0,0);originalCtx.clearRect(0,0,width,height);originalCtx.drawImage(next,0,0);manualRestoreMask=new Uint8Array(width*height);imageData=sourceCtx.getImageData(0,0,width,height);syncSourceSizeFields();resetView();resetRegions();detectCornerColor();detectRegions();}
    function isForeground(index,background,toleranceValue){const data=imageData.data,offset=index*4;if(data[offset+3]<12)return false;if(background.a<12)return true;const distance=Math.sqrt((data[offset]-background.r)**2+(data[offset+1]-background.g)**2+(data[offset+2]-background.b)**2);return distance>toleranceValue;}
    function detectRegions(){if(!imageData)return;setStatus('正在识别图块...');setTimeout(()=>{const {width,height,data}=imageData,background={...rgb(),a:data[3]},visited=new Uint8Array(width*height),queue=new Int32Array(width*height),found=[],minPixels=Number(minArea.value),edge=Number(padding.value);let nextId=1;for(let start=0;start<visited.length;start++){if(visited[start]||!isForeground(start,background,Number(tolerance.value)))continue;let head=0,tail=0,minX=width,minY=height,maxX=0,maxY=0,count=0;queue[tail++]=start;visited[start]=1;while(head<tail){const current=queue[head++],x=current%width,y=(current-x)/width;count++;if(x<minX)minX=x;if(x>maxX)maxX=x;if(y<minY)minY=y;if(y>maxY)maxY=y;const neighbors=[];if(x>0)neighbors.push(current-1);if(x<width-1)neighbors.push(current+1);if(y>0)neighbors.push(current-width);if(y<height-1)neighbors.push(current+width);for(const neighbor of neighbors){if(!visited[neighbor]&&isForeground(neighbor,background,Number(tolerance.value))){visited[neighbor]=1;queue[tail++]=neighbor;}}}if(count>=minPixels){const x=Math.max(0,minX-edge),y=Math.max(0,minY-edge),right=Math.min(width-1,maxX+edge),bottom=Math.min(height-1,maxY+edge);found.push({id:nextId++,x,y,w:right-x+1,h:bottom-y+1,area:count});if(found.length>=maxRegions)break;}}regions=found.sort((a,b)=>a.y-b.y||a.x-b.x);selectedId=regions.length?regions[0].id:null;syncFields();renderRegions();renderOutput();setStatus(regions.length>=maxRegions?'已达到 300 个选区上限，请提高最小像素面积。':'已识别 '+regions.length+' 个图块。');},20);}
    function clampRegion(region){region.x=Math.max(0,Math.min(source.width-1,Math.round(region.x)));region.y=Math.max(0,Math.min(source.height-1,Math.round(region.y)));region.w=Math.max(1,Math.min(source.width-region.x,Math.round(region.w)));region.h=Math.max(1,Math.min(source.height-region.y,Math.round(region.h)));}
    function applyView(){source.style.transform='translate('+Math.round(sourceView.x)+'px,'+Math.round(sourceView.y)+'px) scale('+sourceView.scale+')';requestAnimationFrame(renderRegions);}
    function resetView(){Object.assign(sourceView,{scale:1,x:0,y:0});applyView();}
    function startRegionOperation(event,region){if(editMode!=='select'||event.button!==0)return;event.preventDefault();event.stopPropagation();selectedId=region.id;const rect=source.getBoundingClientRect();regionOperation={box:event.currentTarget,index:regions.indexOf(region),handle:event.target.dataset.handle||'move',startX:event.clientX,startY:event.clientY,scaleX:rect.width/source.width,scaleY:rect.height/source.height,region:{x:region.x,y:region.y,w:region.w,h:region.h}};try{event.currentTarget.setPointerCapture(event.pointerId);}catch(ignore){}syncFields();}
    function moveRegionOperation(event){if(!regionOperation)return;const region=selectedRegion();if(!region)return;const dx=(event.clientX-regionOperation.startX)/regionOperation.scaleX,dy=(event.clientY-regionOperation.startY)/regionOperation.scaleY,start=regionOperation.region,handle=regionOperation.handle,minSize=4;let left=start.x,top=start.y,right=start.x+start.w,bottom=start.y+start.h;if(handle==='move'){left=Math.max(0,Math.min(source.width-start.w,start.x+dx));top=Math.max(0,Math.min(source.height-start.h,start.y+dy));right=left+start.w;bottom=top+start.h;}else{if(handle.indexOf('w')>=0)left+=dx;if(handle.indexOf('e')>=0)right+=dx;if(handle.indexOf('n')>=0)top+=dy;if(handle.indexOf('s')>=0)bottom+=dy;left=Math.max(0,Math.min(source.width-minSize,left));right=Math.max(minSize,Math.min(source.width,right));top=Math.max(0,Math.min(source.height-minSize,top));bottom=Math.max(minSize,Math.min(source.height,bottom));if(right-left<minSize){if(handle.indexOf('w')>=0)left=right-minSize;else right=left+minSize;}if(bottom-top<minSize){if(handle.indexOf('n')>=0)top=bottom-minSize;else bottom=top+minSize;}}region.x=Math.round(left);region.y=Math.round(top);region.w=Math.round(right-left);region.h=Math.round(bottom-top);clampRegion(region);syncFields();positionRegionBox(regionOperation.box,region,regionOperation.index);}
    function endRegionOperation(){if(!regionOperation)return;regionOperation=null;renderRegions();renderOutput();}
    function paintAt(point,restore,refresh){const radius=Number(brush.value)/2,strength=Number(opacity.value)/100,startX=Math.max(0,Math.floor(point.x-radius)),startY=Math.max(0,Math.floor(point.y-radius)),width=Math.min(source.width,Math.ceil(point.x+radius))-startX,height=Math.min(source.height,Math.ceil(point.y+radius))-startY,pixels=sourceCtx.getImageData(startX,startY,width,height),originalPixels=originalCtx.getImageData(startX,startY,width,height);for(let y=0;y<height;y++)for(let x=0;x<width;x++){const dx=startX+x-point.x,dy=startY+y-point.y;if(dx*dx+dy*dy<=radius*radius){const i=(y*width+x)*4,sourceIndex=(startY+y)*source.width+startX+x;if(restore){for(let channel=0;channel<4;channel++)pixels.data[i+channel]=Math.round(pixels.data[i+channel]+(originalPixels.data[i+channel]-pixels.data[i+channel])*strength);if(manualRestoreMask)manualRestoreMask[sourceIndex]=1;}else{pixels.data[i+3]=Math.max(0,Math.round(pixels.data[i+3]*(1-strength)));if(manualRestoreMask)manualRestoreMask[sourceIndex]=0;}}}sourceCtx.putImageData(pixels,startX,startY);if(refresh){imageData=sourceCtx.getImageData(0,0,source.width,source.height);renderOutput();if(refineRegion)drawRefine();}}
    function queuePaintRefresh(){if(paintRefreshQueued)return;paintRefreshQueued=true;requestAnimationFrame(()=>{paintRefreshQueued=false;imageData=sourceCtx.getImageData(0,0,source.width,source.height);if(refineRegion)drawRefine();});}
    function finishPaintRefresh(){imageData=sourceCtx.getImageData(0,0,source.width,source.height);renderOutput();if(refineRegion)drawRefine();}
    function paintStroke(from,to,restore){const radius=Number(brush.value)/2,strength=Number(opacity.value)/100,minX=Math.max(0,Math.floor(Math.min(from.x,to.x)-radius)),minY=Math.max(0,Math.floor(Math.min(from.y,to.y)-radius)),maxX=Math.min(source.width,Math.ceil(Math.max(from.x,to.x)+radius)),maxY=Math.min(source.height,Math.ceil(Math.max(from.y,to.y)+radius)),width=maxX-minX,height=maxY-minY,pixels=sourceCtx.getImageData(minX,minY,width,height),originalPixels=originalCtx.getImageData(minX,minY,width,height),vx=to.x-from.x,vy=to.y-from.y,lengthSq=vx*vx+vy*vy||1;for(let y=0;y<height;y++)for(let x=0;x<width;x++){const px=minX+x,py=minY+y,t=Math.max(0,Math.min(1,((px-from.x)*vx+(py-from.y)*vy)/lengthSq)),dx=px-(from.x+t*vx),dy=py-(from.y+t*vy);if(dx*dx+dy*dy>radius*radius)continue;const i=(y*width+x)*4,sourceIndex=py*source.width+px;if(restore){for(let channel=0;channel<4;channel++)pixels.data[i+channel]=Math.round(pixels.data[i+channel]+(originalPixels.data[i+channel]-pixels.data[i+channel])*strength);if(manualRestoreMask)manualRestoreMask[sourceIndex]=1;}else{pixels.data[i+3]=Math.max(0,Math.round(pixels.data[i+3]*(1-strength)));if(manualRestoreMask)manualRestoreMask[sourceIndex]=0;}}sourceCtx.putImageData(pixels,minX,minY);queuePaintRefresh();}
    function eraseAt(point){paintAt(point,false);}
    function updateBrushRing(event){if((editMode!=='erase'&&!event.ctrlKey&&!event.altKey)||!imageData){brushRing.style.display='none';return;}const rect=source.getBoundingClientRect(),wrap=sourceWrap.getBoundingClientRect();if(event.clientX<rect.left||event.clientX>rect.right||event.clientY<rect.top||event.clientY>rect.bottom){brushRing.style.display='none';return;}const size=Number(brush.value)*rect.width/source.width;brushRing.style.borderColor=event.altKey?'#4ade80':'#fbbf24';brushRing.style.width=size+'px';brushRing.style.height=size+'px';brushRing.style.left=(event.clientX-wrap.left)+'px';brushRing.style.top=(event.clientY-wrap.top)+'px';brushRing.style.display='block';}
    function drawRefine(){if(!refineRegion)return;refineCanvas.width=refineRegion.w;refineCanvas.height=refineRegion.h;refineCtx.clearRect(0,0,refineCanvas.width,refineCanvas.height);refineCtx.drawImage(source,refineRegion.x,refineRegion.y,refineRegion.w,refineRegion.h,0,0,refineRegion.w,refineRegion.h);const pixels=refineCtx.getImageData(0,0,refineCanvas.width,refineCanvas.height),data=pixels.data,bg=rgb(),limit=Number(tolerance.value);for(let y=0;y<refineRegion.h;y++)for(let x=0;x<refineRegion.w;x++){const i=(y*refineRegion.w+x)*4,sourceIndex=(refineRegion.y+y)*source.width+refineRegion.x+x,distance=Math.sqrt((data[i]-bg.r)**2+(data[i+1]-bg.g)**2+(data[i+2]-bg.b)**2);if((!manualRestoreMask||!manualRestoreMask[sourceIndex])&&distance<=limit)data[i+3]=0;}refineCtx.putImageData(pixels,0,0);refineCanvas.style.transform='translate('+Math.round(refineView.x)+'px,'+Math.round(refineView.y)+'px) scale('+refineView.scale+')';}
    function randomRefineBackground(){const hue=Math.floor(Math.random()*360),lightness=32+Math.floor(Math.random()*34);refineWrap.classList.remove('se-bg-light','se-bg-dark');refineWrap.style.backgroundImage='none';refineWrap.style.backgroundColor='hsl('+hue+' 32% '+lightness+'%)';}
    function openRefine(region,index){selectedId=region.id;syncFields();renderRegions();renderOutput();refineRegion=region;Object.assign(refineView,{scale:1,x:0,y:0});document.getElementById('se-refine-title').textContent='精修图块 '+String(index+1).padStart(2,'0');refineName.value=region.name||'';refineModal.hidden=false;randomRefineBackground();drawRefine();}
    function refinePoint(event){const rect=refineCanvas.getBoundingClientRect();return {x:refineRegion.x+Math.max(0,Math.min(refineRegion.w-1,Math.floor((event.clientX-rect.left)*refineRegion.w/rect.width))),y:refineRegion.y+Math.max(0,Math.min(refineRegion.h-1,Math.floor((event.clientY-rect.top)*refineRegion.h/rect.height)))};}
    function updateRefineRing(event){if(!refineRegion){refineRing.style.display='none';return;}const rect=refineCanvas.getBoundingClientRect(),wrap=refineWrap.getBoundingClientRect(),size=Number(brush.value)*rect.width/refineRegion.w;if(event.clientX<rect.left||event.clientX>rect.right||event.clientY<rect.top||event.clientY>rect.bottom){refineRing.style.display='none';return;}refineRing.classList.toggle('restore',event.altKey);refineRing.style.width=size+'px';refineRing.style.height=size+'px';refineRing.style.left=(event.clientX-wrap.left)+'px';refineRing.style.top=(event.clientY-wrap.top)+'px';refineRing.style.display='block';}
    [xInput,yInput,wInput,hInput].forEach(input=>input.addEventListener('input',()=>{const region=selectedRegion();if(!region)return;region.x=Number(xInput.value)||0;region.y=Number(yInput.value)||0;region.w=Number(wInput.value)||1;region.h=Number(hInput.value)||1;clampRegion(region);syncFields();renderRegions();renderOutput();}));
    function pointerImagePoint(event){const rect=source.getBoundingClientRect();return {x:Math.max(0,Math.min(source.width-1,Math.floor((event.clientX-rect.left)*source.width/rect.width))),y:Math.max(0,Math.min(source.height-1,Math.floor((event.clientY-rect.top)*source.height/rect.height)))};}
    function renderDraft(from,to){const metrics=regionCanvasRect(),left=Math.min(from.x,to.x),top=Math.min(from.y,to.y),w=Math.abs(from.x-to.x)+1,h=Math.abs(from.y-to.y)+1;draft.hidden=false;draft.style.left=(metrics.canvasRect.left-metrics.wrapRect.left+left*metrics.scaleX)+'px';draft.style.top=(metrics.canvasRect.top-metrics.wrapRect.top+top*metrics.scaleY)+'px';draft.style.width=Math.max(2,w*metrics.scaleX)+'px';draft.style.height=Math.max(2,h*metrics.scaleY)+'px';}
    sourceWrap.addEventListener('wheel',event=>{if(!imageData)return;event.preventDefault();sourceView.scale=Math.max(.2,Math.min(8,sourceView.scale*(event.deltaY>0?.9:1.1)));applyView();},{passive:false});
    sourceWrap.addEventListener('pointerdown',event=>{if(!imageData||event.button!==1)return;event.preventDefault();regionOperation={kind:'pan',startX:event.clientX,startY:event.clientY,x:sourceView.x,y:sourceView.y};sourceWrap.setPointerCapture(event.pointerId);});sourceWrap.addEventListener('pointermove',event=>{if(!(regionOperation&&regionOperation.kind==='pan'))return;sourceView.x=regionOperation.x+event.clientX-regionOperation.startX;sourceView.y=regionOperation.y+event.clientY-regionOperation.startY;applyView();});['pointerup','pointercancel','lostpointercapture'].forEach(name=>sourceWrap.addEventListener(name,()=>{if(regionOperation&&regionOperation.kind==='pan')regionOperation=null;}));
    source.addEventListener('pointerdown',event=>{if(!imageData)return;if(pickMode&&event.button===0){event.preventDefault();picking=true;source.setPointerCapture(event.pointerId);pickBackground(event);return;}if(event.button===2&&editMode==='select'){event.preventDefault();bulkStart=pointerImagePoint(event);source.setPointerCapture(event.pointerId);renderDraft(bulkStart,bulkStart);return;}if(event.button!==0)return;manualStart=pointerImagePoint(event);source.setPointerCapture(event.pointerId);renderDraft(manualStart,manualStart);});
    source.addEventListener('pointermove',event=>{if(picking){pickBackground(event);return;}if(manualStart)renderDraft(manualStart,pointerImagePoint(event));if(bulkStart)renderDraft(bulkStart,pointerImagePoint(event));});
    source.addEventListener('contextmenu',event=>event.preventDefault());
    source.addEventListener('pointerleave',()=>{if(!eraseOperation)brushRing.style.display='none';});
    ['pointerup','pointercancel','lostpointercapture'].forEach(name=>source.addEventListener(name,event=>{if(picking){setPickMode(false);setStatus('已停止吸取背景颜色。');return;}if(brushAdjust){brushAdjust=null;return;}if(eraseOperation){eraseOperation=null;lastPaintPoint=null;brushRing.style.display='none';setStatus('已应用笔刷。');return;}if(bulkStart){const end=pointerImagePoint(event),left=Math.min(bulkStart.x,end.x),top=Math.min(bulkStart.y,end.y),right=Math.max(bulkStart.x,end.x),bottom=Math.max(bulkStart.y,end.y),removed=regions.filter(region=>region.x<right&&region.x+region.w>left&&region.y<bottom&&region.y+region.h>top);if(removed.length){deletedRegions.push(...removed);regions=regions.filter(region=>!removed.includes(region));selectedId=regions.length?regions[0].id:null;syncFields();renderRegions();renderOutput();setStatus('已删除 '+removed.length+' 个选区。');}draft.hidden=true;bulkStart=null;return;}if(!manualStart)return;const end=pointerImagePoint(event),x=Math.min(manualStart.x,end.x),y=Math.min(manualStart.y,end.y),w=Math.abs(manualStart.x-end.x)+1,h=Math.abs(manualStart.y-end.y)+1;draft.hidden=true;if(w>3&&h>3){const region={id:Date.now()+Math.random(),x,y,w,h,area:w*h};regions.push(region);selectedId=region.id;syncFields();renderRegions();renderOutput();setStatus('已新增手动选区。');}manualStart=null;}));
    function loadImage(file){if(!file||!file.type.startsWith('image/'))return;fileBase=(file.name.replace(/\.[^.]+$/,'')||'sprites').replace(/[^a-zA-Z0-9_-]+/g,'_');const image=new Image(),url=URL.createObjectURL(file);image.onload=()=>{URL.revokeObjectURL(url);let width=image.naturalWidth,height=image.naturalHeight;if(width*height>maxPixels){const scale=Math.sqrt(maxPixels/(width*height));width=Math.max(1,Math.round(width*scale));height=Math.max(1,Math.round(height*scale));setStatus('原图较大，已缩小后识别。');}source.width=original.width=width;source.height=original.height=height;manualRestoreMask=new Uint8Array(width*height);sourceCtx.clearRect(0,0,width,height);sourceCtx.drawImage(image,0,0,width,height);originalCtx.clearRect(0,0,width,height);originalCtx.drawImage(image,0,0,width,height);imageData=sourceCtx.getImageData(0,0,width,height);syncSourceSizeFields();document.getElementById('se-file-name').textContent=file.name;document.getElementById('se-file-meta').textContent=width+' x '+height+' px';sourceEditor.classList.add('show');resultEditor.classList.add('show');resultEmpty.style.display='none';drop.style.display='none';detectCornerColor();resetView();resetRegions();requestAnimationFrame(()=>{renderRegions();detectRegions();});};image.onerror=()=>setStatus('图片读取失败，请换一张图片重试。');image.src=url;}
    refineCanvas.addEventListener('wheel',event=>{event.preventDefault();if(event.ctrlKey){brush.value=Math.max(Number(brush.min),Math.min(Number(brush.max),Number(brush.value)+(event.deltaY>0?-2:2)));brush.dispatchEvent(new Event('input'));updateRefineRing(event);return;}refineView.scale=Math.max(.3,Math.min(10,refineView.scale*(event.deltaY>0?.9:1.1)));drawRefine();},{passive:false});
    refineCanvas.addEventListener('pointerdown',event=>{if(event.button===1){event.preventDefault();refinePan={x:event.clientX,y:event.clientY,viewX:refineView.x,viewY:refineView.y};refineCanvas.setPointerCapture(event.pointerId);return;}if(event.button===0){event.preventDefault();if(event.ctrlKey){refineBrushAdjust={startY:event.clientY,value:Number(brush.value)};refineCanvas.setPointerCapture(event.pointerId);return;}refinePaint=event.altKey?'restore':'erase';refineLastPaint=refinePoint(event);refineCanvas.setPointerCapture(event.pointerId);paintStroke(refineLastPaint,refineLastPaint,refinePaint==='restore');}});
    refineCanvas.addEventListener('pointermove',event=>{updateRefineRing(event);if(refinePan){refineView.x=refinePan.viewX+event.clientX-refinePan.x;refineView.y=refinePan.viewY+event.clientY-refinePan.y;drawRefine();return;}if(refineBrushAdjust){brush.value=Math.max(Number(brush.min),Math.min(Number(brush.max),refineBrushAdjust.value+refineBrushAdjust.startY-event.clientY));brush.dispatchEvent(new Event('input'));return;}if(refinePaint){const point=refinePoint(event);paintStroke(refineLastPaint,point,refinePaint==='restore');refineLastPaint=point;}});
    ['pointerup','pointercancel','lostpointercapture'].forEach(name=>refineCanvas.addEventListener(name,()=>{if(refinePaint)finishPaintRefresh();refinePaint=null;refinePan=null;refineBrushAdjust=null;refineLastPaint=null;refineRing.style.display='none';}));refineCanvas.addEventListener('pointerleave',()=>{if(!refinePaint)refineRing.style.display='none';});
    refineBackground.addEventListener('click',randomRefineBackground);refineName.addEventListener('input',()=>{if(refineRegion)refineRegion.name=refineName.value.trim().replace(/[\\/:*?"<>|]+/g,'_');});refineClose.addEventListener('click',()=>{refineModal.hidden=true;refineRegion=null;renderRegions();renderOutput();setStatus('已完成精修。');});refineModal.addEventListener('click',event=>{if(event.target===refineModal)refineClose.click();});
    fileInput.addEventListener('change',event=>loadImage(event.target.files[0]));['dragenter','dragover'].forEach(name=>drop.addEventListener(name,event=>{event.preventDefault();drop.classList.add('dragover');}));['dragleave','drop'].forEach(name=>drop.addEventListener(name,event=>{event.preventDefault();drop.classList.remove('dragover');}));drop.addEventListener('drop',event=>loadImage(event.dataTransfer.files[0]));resizeWInput.addEventListener('input',()=>{if(lockRatio.checked&&source.width)resizeHInput.value=Math.max(1,Math.round((Number(resizeWInput.value)||source.width)*source.height/source.width));});resizeHInput.addEventListener('input',()=>{if(lockRatio.checked&&source.height)resizeWInput.value=Math.max(1,Math.round((Number(resizeHInput.value)||source.height)*source.width/source.height));});resizeApply.addEventListener('click',()=>{if(!imageData)return;const w=Math.max(1,Math.min(8000,Number(resizeWInput.value)||source.width)),h=Math.max(1,Math.min(8000,Number(resizeHInput.value)||source.height));replaceSource(w,h,(ctx)=>ctx.drawImage(source,0,0,source.width,source.height,0,0,w,h));setStatus('已应用源图缩放。');});
    colorInput.addEventListener('input',()=>{colorValue.textContent=colorInput.value.toUpperCase();renderOutput();});cornerButton.addEventListener('click',()=>{detectCornerColor();renderOutput();setStatus('已从图片边角重新取色。');});pickButton.addEventListener('click',()=>{if(!imageData)return;setPickMode(!pickMode);setStatus(pickMode?'请在源图上按住左键吸取背景颜色。':'已取消吸取背景。');});detectButton.addEventListener('click',detectRegions);clearButton.addEventListener('click',()=>{deletedRegions.push(...regions);regions=[];selectedId=null;syncFields();renderRegions();renderOutput();setStatus('已清空全部选区。');});deleteButton.addEventListener('click',()=>{const region=selectedRegion();if(region)removeRegion(region.id);});restoreButton.addEventListener('click',()=>{if(!deletedRegions.length)return;regions.push(...deletedRegions.splice(0));regions.sort((a,b)=>a.y-b.y||a.x-b.x);selectedId=regions.length?regions[0].id:null;syncFields();renderRegions();renderOutput();setStatus('已恢复删除的选区。');});fitButton.addEventListener('click',resetView);boxesButton.addEventListener('click',()=>{showBoxes=!showBoxes;boxesButton.textContent=showBoxes?'隐藏框':'显示框';renderRegions();});labelsButton.addEventListener('click',()=>{showLabels=!showLabels;labelsButton.textContent=showLabels?'隐藏编号':'显示编号';renderRegions();});cancelRefineButton.addEventListener('click',()=>{setEditMode('select');setStatus('已取消精修。');});document.querySelectorAll('.se-mode .se-button').forEach(button=>button.addEventListener('click',()=>{setEditMode(button.dataset.mode);setStatus(button.dataset.mode==='erase'?'橡皮擦模式已开启。':'选区编辑模式已开启。');}));
    function crcTable(){const table=new Uint32Array(256);for(let n=0;n<256;n++){let value=n;for(let k=0;k<8;k++)value=(value&1)?(0xedb88320^(value>>>1)):(value>>>1);table[n]=value>>>0;}return table;}const crcLookup=crcTable();function crc32(bytes){let value=0xffffffff;for(const byte of bytes)value=crcLookup[(value^byte)&255]^(value>>>8);return (value^0xffffffff)>>>0;}function u16(view,offset,value){view.setUint16(offset,value,true);}function u32(view,offset,value){view.setUint32(offset,value,true);}function joinBytes(parts){const length=parts.reduce((sum,part)=>sum+part.length,0),output=new Uint8Array(length);let offset=0;parts.forEach(part=>{output.set(part,offset);offset+=part.length;});return output;}
    function makeZip(files){const encoder=new TextEncoder(),locals=[],centrals=[];let offset=0;files.forEach(file=>{const name=encoder.encode(file.name),data=file.data,crc=crc32(data),local=new Uint8Array(30+name.length+data.length),localView=new DataView(local.buffer);u32(localView,0,0x04034b50);u16(localView,4,20);u16(localView,6,0);u16(localView,8,0);u16(localView,10,0);u16(localView,12,0);u32(localView,14,crc);u32(localView,18,data.length);u32(localView,22,data.length);u16(localView,26,name.length);u16(localView,28,0);local.set(name,30);local.set(data,30+name.length);locals.push(local);const central=new Uint8Array(46+name.length),centralView=new DataView(central.buffer);u32(centralView,0,0x02014b50);u16(centralView,4,20);u16(centralView,6,20);u16(centralView,8,0);u16(centralView,10,0);u16(centralView,12,0);u16(centralView,14,0);u32(centralView,16,crc);u32(centralView,20,data.length);u32(centralView,24,data.length);u16(centralView,28,name.length);u16(centralView,30,0);u16(centralView,32,0);u16(centralView,34,0);u16(centralView,36,0);u32(centralView,38,0);u32(centralView,42,offset);central.set(name,46);centrals.push(central);offset+=local.length;});const centralData=joinBytes(centrals),end=new Uint8Array(22),endView=new DataView(end.buffer);u32(endView,0,0x06054b50);u16(endView,4,0);u16(endView,6,0);u16(endView,8,files.length);u16(endView,10,files.length);u32(endView,12,centralData.length);u32(endView,16,offset);u16(endView,20,0);return new Blob([joinBytes([...locals,centralData,end])],{type:'application/zip'});}
    function canvasBytes(canvas){return new Promise((resolve,reject)=>canvas.toBlob(blob=>blob?blob.arrayBuffer().then(buffer=>resolve(new Uint8Array(buffer))).catch(reject):reject(new Error('PNG 生成失败')),'image/png'));}
    async function chargeAndExport(){if(!regions.length||isExporting)return;isExporting=true;updateActions();exportButton.textContent='正在导出...';setStatus('正在校验导出次数...');try{const response=await fetch('/api/tool_api.asp?a=sprite_export',{method:'POST',credentials:'same-origin'}),payload=await response.json();if(!payload.success){if((payload.message||'').indexOf('登录')>=0){window.location.href='/login.html?redirect=/sprite_extract.asp';return;}throw new Error(payload.message||'导出失败');}balance.textContent=payload.data.token_balance;setStatus('正在生成 ZIP 文件...');const files=[],prefix=(prefixInput.value.trim()||fileBase).replace(/[^a-zA-Z0-9_-]+/g,'_');for(let index=0;index<regions.length;index++){const canvas=spriteCanvas(regions[index]),name=(regions[index].name||prefix+'_'+String(index+1).padStart(3,'0')).replace(/[\\/:*?"<>|]+/g,'_');files.push({name:name+'_'+canvas.width+'x'+canvas.height+'.png',data:await canvasBytes(canvas)});}const url=URL.createObjectURL(makeZip(files)),link=document.createElement('a');link.href=url;link.download=prefix+'_sprites.zip';document.body.appendChild(link);link.click();link.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);setStatus('已导出 '+regions.length+' 张 PNG，本次消耗 1 次，剩余 '+payload.data.token_balance+' 次。');}catch(error){setStatus(error.message||'导出失败，请稍后重试。');}finally{isExporting=false;exportButton.textContent='导出全部 PNG';updateActions();}}
    exportButton.addEventListener('click',chargeAndExport);
})();