s=open(r'..\public\js\app-filetree.js',encoding='utf-8').read()
print('minBtn bind count:', s.count('if (minBtnEl) minBtnEl.onclick'))
c=open(r'..\public\css\style-filetree.css',encoding='utf-8').read()
print('css dock comment blocks:', c.count('文件面板最小化 dock'))
f=open(r'..\public\css\ft-dock.css',encoding='utf-8').read()
print('ft-dock.css .ft-dock blocks:', f.count('.ft-dock {'))
i=c.find('/* ===== 文件面板最小化 dock')
j=c.find('/* ===== 文件面板最小化 dock', i+10)
print('dup in style-filetree:', j)
